#pragma once

enum class Color
{
    Border,
    Barrel,
    Tank,
    TeamBlue,
    TeamRed,
    TeamPurple,
    TeamGreen,
    Shiny,
    EnemySquare,
    EnemyTriangle,
    EnemyPentagon,
    EnemyCrasher,
    Neutral,
    ScoreboardBar,
    Box,
    EnemyTank,
    NecromancerSquare,
    Fallen
};

enum class Tank
{
    Basic = 0,
    Twin = 1,
    Triplet = 2,
    TripleShot = 3,
    QuadTank = 4,
    OctoTank = 5,
    Sniper = 6,
    MachineGun = 7,
    FlankGuard = 8,
    TriAngle = 9,
    Destroyer = 10,
    Overseer = 11,
    Overlord = 12,
    TwinFlank = 13,
    PentaShot = 14,
    Assassin = 15,
    ArenaCloser = 16,
    Necromancer = 17,
    TripleTwin = 18,
    Hunter = 19,
    Gunner = 20,
    Stalker = 21,
    Ranger = 22,
    Booster = 23,
    Fighter = 24,
    Hybrid = 25,
    Manager = 26,
    Mothership = 27,
    Predator = 28,
    Sprayer = 29,
    Trapper = 30,
    GunnerTrapper = 32,
    Overtrapper = 33,
    MegaTrapper = 34,
    TriTrapper = 35,
    Smasher = 36,
    Landmine = 37,
    AutoGunner = 39,
    Auto5 = 40,
    Auto3 = 41,
    SpreadShot = 42,
    Streamliner = 43,
    AutoTrapper = 44,
    DominatorD = 45,
    DominatorG = 46,
    DominatorT = 47,
    Battleship = 48,
    Annihilator = 49,
    AutoSmasher = 50,
    Spike = 51,
    Factory = 52,
    Skimmer = 54,
    Rocketeer = 55
};
